### ISSUE TITLE
Moving scheduled time not accurate

### ISSUE THREAD

**Issue by nezaboravi** [silasmontgomery/CakePHP-Full-Calendar-Plugin#10]
When i am moving scheduled event, display time is not accurate and its impossible to move it from 8:00 am to 9:00, usually it writes 8:50 or 9:20. Also, fiebug reports a bunch of errors:
Missing View

Error: The view for EventsController::update() was not found.

Error: Confirm you have created the file: E:\crm\app\Plugin\FullCalendar\View\Events\update.ctp

Notice: If you want to customize this error message, create app\View\Errors\missing_view.ctp
Stack Trace

```
CORE\Cake\View\View.php line 460 → View->_getViewFileName(null)
CORE\Cake\Controller\Controller.php line 962 → View->render(null, null)
CORE\Cake\Routing\Dispatcher.php line 110 → Controller->render()
CORE\Cake\Routing\Dispatcher.php line 85 → Dispatcher->_invoke(EventsController, CakeRequest, CakeResponse)
APP\webroot\index.php line 96 → Dispatcher->dispatch(CakeRequest, CakeResponse)
```

(default) 9 queries took 0 ms Nr    Query   Error   Affected    Num. rows   Took (ms)
1   SELECT COUNT(_) AS `count` FROM `crm`.`events` AS `Event` WHERE `Event`.`id` = 1        1   1   0
2   SELECT COUNT(_) AS `count` FROM `crm`.`events` AS `Event` WHERE `Event`.`id` = 1        1   1   0
3   UPDATE `crm`.`events` SET `start` = '2012-3-9 8:50:00', `modified` = '2012-03-08' WHERE `crm`.`events`.`id` = '1'       1   1   0
4   SELECT COUNT(_) AS `count` FROM `crm`.`events` AS `Event` WHERE `Event`.`id` = 1        1   1   0
5   SELECT COUNT(_) AS `count` FROM `crm`.`events` AS `Event` WHERE `Event`.`id` = 1        1   1   0
6   UPDATE `crm`.`events` SET `end` = '2012-3-9 9:21:00', `modified` = '2012-03-08' WHERE `crm`.`events`.`id` = '1'     1   1   0
7   SELECT COUNT(_) AS `count` FROM `crm`.`events` AS `Event` WHERE `Event`.`id` = 1        1   1   0
8   SELECT COUNT(_) AS `count` FROM `crm`.`events` AS `Event` WHERE `Event`.`id` = 1        1   1   0
9   UPDATE `crm`.`events` SET `all_day` = '0', `modified` = '2012-03-08' WHERE `crm`.`events`.`id` = '1'        0   0   0

**Comment by silasmontgomery** [comment]
Due to the age of this issue I'm going to close it. If you are still having problems please start a new ticket. Thanks!
