### ISSUE TITLE
Plugin breaks links

### ISSUE THREAD

**Issue by gerrymcdonnell** [silasmontgomery/CakePHP-Full-Calendar-Plugin#11]
Hi im using elements for different menus in my site using cakephp to create the links eg; echo $this->Html->link('Home',array('controller'=>'users','action'=>'home'));

My links all break when using the full_calender plugin 2.0 branch when i click the link to the full calender page located at; http://localhost/mysite/full_calendar

all the links in my element are broken and become;

http://localhost/mysite/full_calendar/home/

instead of

http://localhost/mysite/home

ive installed the plugin in app/plugin

Im using the controller name and view in my links in the element so whats going wrong?

**Comment by srs81** [comment]
Make sure to specify a "null" plugin for correcting the view, that should solve the problem:

$this->Html->link('Home',array('plugin'=>'', 'controller'=>'users','action'=>'home'));
