### ISSUE TITLE
Add more event tables

### ISSUE THREAD

**Issue by vaanbooch** [silasmontgomery/CakePHP-Full-Calendar-Plugin#14]
Hello,

I have currently a website, which has already several types of events, based in separate tables. 

I was wondering is it possible to integrate them in your FullCalendar plugin. As far as I can see, there are the following solutions:
1. To try to modify your plugin and make it fetch the data from the existing tables and assign a separate event type to each of them.
2. To modify my existing code, e.g. to duplicate the present data and put it in events table with the corresponding event type. And when the data in the existing tables is modified, it should be synchronized in the events table.

Could you please give some guidelines to solve the problem?

Thanks a lot!

Regards,
VaanBooch

**Comment by srs81** [comment]
(Note: I'm not the author of this plugin, just someone who uses it.)

I suspect the easiest way might be to modify the Events model, controller and views, and replace the EventTypes relationship with your own existing types.

Or if you don't use your existing types in other places in your website, you can probably import the data into EventTypes in FullCalendar plugin.

Finally: if you need to keep both and these are the same, maybe create a MySQL View to expose your existing types as an EventType? This depends on how complicated your types database table is though.

**Comment by vaanbooch** [comment]
Thanks srs81,

You are right. Each of the existing event tables has it's own CRUD operations and it will be better to keep them working.
In fact I plan to use FullCalendar in read-only mode - just for visualize all event data types in one place. If some event needs to be viewed or modified, etc., FullCalendar will point the user to the corresponding table CRUD operations

I think if I modify the events_controller feed() function, aggergate all existing data by type and pass it to FullCalendar it will work. Then I will need just to restrict / cleanup the not needed parts of the code in the plugin's controllers and views.

What do you think about it?

Regards.

**Comment by srs81** [comment]
Hi, unfortunately I don't know that much about the plugin yet - am just using it and have a very superficial knowledge. :/ What you proposed sounds reasonable enough - sorry I couldn't help more.

**Comment by silasmontgomery** [comment]
I'm going to close this ticket but please re-post if you're still having problems and I'll help if I can.
