### ISSUE TITLE
Unable to show the event after clicking the event in the calendar

### ISSUE THREAD

**Issue by vylai** [silasmontgomery/CakePHP-Full-Calendar-Plugin#15]
Hi,
I am able to show the events I created in the calendar just fine
However, i am unable to show the details of the event by clicking on it in the calendar view and it shows this:

"Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404"

Can anyone help me?

I also got another problem which is the color for the event type
The color didn't show in the calendar
Thanks in advance

**Comment by impliedn** [comment]
having the same issue. using croogo. even added patch. still nothing. please assist pretty please!!!

**Comment by silasmontgomery** [comment]
Hey guys, sorry for the late response! The problem was most likely due to the installation path of Cake/FullCalender and has been resolved in the latest release (v2.1). I'm going to go ahead and close this due to it's age but be sure to respond if you're still in need of some help.
