### ISSUE TITLE
Add Event in the calendar directly (when I click on the calendar) and saving data in database

### ISSUE THREAD

**Issue by sindouda** [silasmontgomery/CakePHP-Full-Calendar-Plugin#18]
Hy,
I am using the plugin FullCalendar for CakePhp.
But ,my problem is how can I add a new event when I click on the calendar and save data in database.
I added this to the file ready.js:
selectable: true,
            selectHelper: true,
            select: function(start, end, allDay) {
                var title = prompt('Event Title:');
                if (title) {
                    calendar.fullCalendar('renderEvent',
                        {
                            title: title,
                            start: start,
                            end: end,
                            allDay: allDay
                        },
                        true // make the event "stick"
                    );
                }
                calendar.fullCalendar('unselect');
            },

The event is added on the calendar but when I refresh the event disappear also when I  check the database this event is not added.
Please how can I get data and save it ????

**Comment by silasmontgomery** [comment]
I apologize for the very late reply. Were you able to figure out your problem?
