### ISSUE TITLE
Missing Controller (FullCalendarController.php) & Other Issues

### ISSUE THREAD

**Issue by ThatGirlSlays** [silasmontgomery/CakePHP-Full-Calendar-Plugin#19]
I followed the install instructions to the letter and this is also not my first time installing a plugin.

When I navigate to http://www.mydomain.com/cake_directory/full_controller, I receive a missing controller error message. I have loaded the plugin at the bottom of my bootstrap as instructed.

I am using CakePHP 2.2

**Comment by ThatGirlSlays** [comment]
Ok basically what I ended up doing was install this NOT as a plugin but just mixed in with the rest of my files (as in I placed the plugin controller files among the rest of my controllers, etc). This resolved the fact that FullCalendarController.php could not be found.

However, another issue arose and that was that FullCalendarAppController.php and FullCalendarAppModel.php were not being read/extended/loaded. I had to edit all the plugin controller and model files to extend to the standard AppController and AppModel instead of the plugin FullCalendarAppController and FullCalendarAppModel.

However, I am facing yet ANOTHER issue in that even AFTER removing the loading of the plugin from bootstrap.php and deleting the FullCalendar folder from app/Plugin, I still receive an error that “the application is trying to load a file from the FullCalendar plugin”. Obviously that file does not exist because I deleted the FullCalendar folder, but I also removed the loading of the plugin. I emptied my cache.

**Comment by JPHanke** [comment]
Hi there, 

I'm trying to install this plugin and having this same problem. I've tried to do what bhndbrwneyes said in the last post but I'm still can't use the plugin. Can someone help me to use it? 

I'm using Cake PHP 2.3

**Comment by silasmontgomery** [comment]
I'll need the details of your installation in order to help. Is the plugin installed in the root of your domain (http://www.yourdomain.com/full_calendar)? Are you using the latest code? (I just updated it yesterday). What message(s) or errors are you getting?

**Comment by JPHanke** [comment]
Hi silasmontgomery.

Yes, I've downloaded the plugin about 4 hours ago. Well, I've followed the 4 steps described in the readme file and found the errors mentioned by bhndbrwneyes. Found this topic and followed the solution described here.

In the end, I can access mydomain.com/cake/full_calendar but can't view the calender itself, only 3 buttons related to create, manage and edit events.

The messages that I'm getting are:

Error: The action events is not defined in controller FullCalendarController
Error: Create FullCalendarController::events() in file: app\Controller\FullCalendarController.php.

I'm sending a print of the error screen. I hope it can help a little more.

Thanks for the help!
![erro](https://f.cloud.github.com/assets/4458358/519424/4760de14-bf17-11e2-9cf2-96955ed63db0.jpg)

**Comment by silasmontgomery** [comment]
My first suggestion would be to re-install Full Calendar as a plugin (following the readme) as I don't suggest and can't vouch for the method used by bhndbrwneyes. Once you've done that let me know what you see when trying to view the calendar at mydomain.com/cake/full_calendar (assuming /cake/ is where your cake installation lives).

**Comment by JPHanke** [comment]
Well, looks like I was doing some confusion over here. When I re-installed the plugin something came to my mind.
My aplication uses AUTH componente so I just add a "before filter" in the controllers and it's work perfectly!

silasmontgomery, thanks for the patience and the help!

**Comment by silasmontgomery** [comment]
Great to hear! I have a feeling that was most likely bhndbrwneyes problem also. Enjoy!

**Comment by ThatGirlSlays** [comment]
JPHanke, what exactly did you add in the beforeFilter because my temporary solution wasn't a solution after all and I ran into additional issues.

**Comment by JPHanke** [comment]
Hi there!

This is the beforeFilter function I've added in the FullCalendarAppController:

public function beforeFilter() {
        parent::beforeFilter();
        $this->Auth->allow();
}

Hope it helps you!
