### ISSUE TITLE
remove old syntax

### ISSUE THREAD

**Issue by dereuromark** [silasmontgomery/CakePHP-Full-Calendar-Plugin#2]
in your index.ctp it should read:

echo $this->Javascript->link('/full_calendar/js/jquery-1.5.min', false);
echo $this->Javascript->link('/full_calendar/js/jquery-ui-1.8.9.custom.min', false);
echo $this->Javascript->link('/full_calendar/js/fullcalendar.min', false);
echo $this->Javascript->link('/full_calendar/js/jquery.qtip-1.0.0-rc3.min', false);
echo $this->Javascript->link('/full_calendar/js/ready', false);
echo $this->Html->css('/full_calendar/css/fullcalendar', null, array('inline' => false));

**Comment by silasmontgomery** [comment]
Good catch! After a quick check I found that the Javascript helper is being deprecated all together. Instead I replaced it with the HTML helper script method.
