### ISSUE TITLE
tablePrefix in Database for plugin

### ISSUE THREAD

**Issue by peerrabe** [silasmontgomery/CakePHP-Full-Calendar-Plugin#3]
Hello,

i try to use tablePrefix for this plugin and set the prefix in FullCalendarAppModel, but for associations it is not considered. i set in model associations the plugin name and success! now i can use tablePrefixes...

example for EventType

```
var $hasMany = array(
    'Event' => array(
        'className' => 'FullCalendar.Event',
        'foreignKey' => 'event_type_id',
        'dependent' => false,
    )
); 
```

greetings

**Comment by silasmontgomery** [comment]
Great catch! I was able to recreate the problem and your solution solved it (and works with or without using tablePrefix). I've updated className in both the event and event_type models to include the plugin name.

**Comment by peerrabe** [comment]
Hello Silas,

your example site is down...

Am 23.09.11 02:48, schrieb Silas Montgomery:

> Great catch! I was able to recreate the problem and your solution solved it (and works with or without using tablePrefix). I've updated className in both the event and event_type models to include the plugin name.
