### ISSUE TITLE
add non minified source files

### ISSUE THREAD

**Issue by SibLiant** [silasmontgomery/CakePHP-Full-Calendar-Plugin#4]
Great pluggin.  Thank you for your work.  I would like to add this to my project but would appreciate if you added the non minified versions of your js.  Thanks again.  Also out of the box the calendar did not display events.

EDIT: nevermind.. I realized the fullCalendar was an additional pluggin.

**Comment by silasmontgomery** [comment]
First, thanks for your interest and you are correct.. jQuery, jQuery-ui, jQuery-qTip, and fullCalendar are all existing open source projects compiled into this plugin and are in minified form. If you'd like the source for any of those files you can easily grab them from the appropriate sites. As far as your problem viewing events out of the box.. did you resolve it and if so what was the problem? This type of info would be good in creating a FAQ. If you're still having a problem let me know and I can help you troubleshoot.

**Comment by djonatanb** [comment]
I'm facing the, apparently, same issue.
The returned error is 
The requested URL /full_calendar/events/feed was not found on this server.

It was, apparently, solved by changing the ready.js 

``` javascript
events: "/full_calendar/events/feed",
```

to

``` javascript
events: "/FillYourProjectFolder/full_calendar/events/feed",
```

I'm not sure yet if it's a mistake or if some kind of misuse... but if it was a mistake I'm probably going to find how to make it automatically

**Comment by silasmontgomery** [comment]
You're right. The URI "/full_calendar/events/feed" makes the assumption that full_calendar is located at "http://www.yourdomain.com/full_calendar". This issue is very old (sorry about that), but let me know if you're having any more problems.
