### ISSUE TITLE
Event is not shown

### ISSUE THREAD

**Issue by peerrabe** [silasmontgomery/CakePHP-Full-Calendar-Plugin#5]
if an event is not allday and starts in month before and ends in the month after the selected month in calendar, so the event is not shown.
my simple approach is to set explicitly the end for every event and make changes to line 78 from
$conditions = array('conditions' => array('UNIX_TIMESTAMP(start) >=' => $vars['start'], 'UNIX_TIMESTAMP(start) <=' => $vars['end']));

to

$conditions = array('conditions' => array('UNIX_TIMESTAMP(end) >=' => $vars['start'], 'UNIX_TIMESTAMP(start) <=' => $vars['end']));

that works for me, because i don't use allday events, so there is set an vaild end...
the drag&drop feature sets an ugly 1970-01-01 01:00:00 date for allday events end

greetings

**Comment by peerrabe** [comment]
the 1970 problem i've solved in my eventDrop definition and set end = start on allday...

**Comment by silasmontgomery** [comment]
Sorry for such a long delay. I wasn't able to recreate this issue. Are you still having any problems?

**Comment by silasmontgomery** [comment]
This issue is pretty old so I'm going to close it. Feel free to open a new one if you're having any problems.
