### ISSUE TITLE
events are not displayed in the calendar

### ISSUE THREAD

**Issue by thina128** [silasmontgomery/CakePHP-Full-Calendar-Plugin#6]
hai.Let me explain in short my problems.
-im new to cakephp.
-i need to develop a timesheet system using cakephp.
-i need to include a fullcalendar in my cakephp.(which i've done using the silas/cakephp-full-calendar-plugin)
-i want to make the calendar to be editable.(i've changed the editable:false to editable:true in the ready.js)
-BUT i CANT view the events in the calendar eventhough i've created the events and CAN view it in the events/index, and so on.
-MAIN purpose of timesheet cakephp is to calculate total time spent for a project, which will be generated automatically.(need coding for this)
-how to edit the events in the calendar ?and where and how to edit the code?pls help me out.
its my BIG project..

**Comment by silasmontgomery** [comment]
Sorry for such a long delay. Still working on this project?

**Comment by silasmontgomery** [comment]
This is a pretty old issue so I'm going to close the ticket. Let me know if I can still help.
