### ISSUE TITLE
How quickly can we get a Cakephp 2.0.4 version up and running?

### ISSUE THREAD

**Issue by 1dolinski** [silasmontgomery/CakePHP-Full-Calendar-Plugin#7]
Following the instructions in the current form does not work. Any ideas of how to get this up and running in cake ver. 2.0.4?

**Comment by vanvolkan** [comment]
For those wanting to get this to work with CakePHP 2...There are a few things you will need to do - mainly just renaming files/moving files

Here's how I got mine to work:
- First off rename the folders:
  /config --> /Config
  /controllers --> /Controller
  /models --> /Model
  /views --> /View

Now move the files /full_calendar_app_controller.php AND /full_calendar_app_model.php to their respective folders (move full_calendar_app_controller.php file to the /Controller folder, and move the full_calendar_app_model.php file to the /Model folder)

Now go through the /Controller folder and rename all files to be camel cased - e.g - event_types_controller.php --> EventTypesController.php , events_controller.php --> EventsController.php ... etc - make sure you do ALL the files, including the app_controller file you moved in here)

Next you do the same for the /Model directory, renaming all model filenames to camel cased, e.g. event.php --> Event.php, event_type.php --> EventType.php ... etc - make sure you do ALL files (including the app_model file you moved in here)

Move over to the /View directory, here you just need to rename the folders to camel cased (the files in the folders (e.g - add.ctp can remain as they are)) - so rename /View/event_types/ to /View/EventTypes/ .. etc

/webroot can remain as is

One last thing I had to do, in /Controller/FullCalendarAppController.php - it was using an old helper 'Javascript' - which has been deprecated - so I changed the following line:
var $helpers = array('Html', 'Form', 'Session', 'Javascript');
to:
var $helpers = array('Html', 'Form', 'Session', 'Js' => array('Jquery'));

Don't forget to load the plugin in the bootstrap.php file
(in /app/Config/bootstrap.php right at the bottom, you can either load ALL plugins with CakePlugin::loadAll(); ... OR just load our FullCalendar plugin with: CakePlugin::load('FullCalendar');

**Comment by 1dolinski** [comment]
Hey cool! thanks!

**Comment by silasmontgomery** [comment]
Master is now compatible with CakePHP 2.x. Sorry for the major delay on this but thanks to OverFlow636 for getting my ass moving on this again.
