### ISSUE TITLE
no events on calendar

### ISSUE THREAD

**Issue by tedhill** [silasmontgomery/CakePHP-Full-Calendar-Plugin#9]
Hi Silas,

I cannot see the events on my calendar :(

I downloaded the zip silasmontgomery-CakePHP-Full-Calendar-Plugin-v2.0-0-gcc9fe66.zip CakePHP-Full-Calendar-Plugin 

I have CakePHP 2.1 
installed in app/Plugin/FullCalendar
I created the DB tables
I see the calendar at localhost/full_calendar
I added event_types

I added events 

1   1   Lorraine        2012-02-06 18:50:00 2012-02-06 20:50:00 1   Scheduled   1   2012-02-06  2012-02-06
2   1   rosemere        2012-02-09 15:52:00 2012-02-09 18:52:00 0   In Progress 1   2012-02-06  2012-02-06

There are no events on the calendar....

**Comment by silasmontgomery** [comment]
CakePHP 2.1 is still in beta and I haven't tested it yet.. thats most likely not the issue but you never know. I'll grab a copy and test but in the mean time let's see what we can find out:

If you're able to add and view events from "localhost/full_calendar/events" but not see them on the calendar at "localhost/full_calendar" it's most likely a problem with the javascript in "FullCalendar/webroot/js/ready.js" trying to pull the events from "localhost/full_calendar/events/feed" via AJAX. Try to view the feed url directly and see if you get some errors like this:

Notice (8): Undefined index: start [APP/Plugin/FullCalendar/Controller/EventsController.php, line 83]
Notice (8): Undefined index: end [APP/Plugin/FullCalendar/Controller/EventsController.php, line 83]
Notice (8): Undefined variable: data [APP/Plugin/FullCalendar/Controller/EventsController.php, line 104]

**Comment by silasmontgomery** [comment]
Ok, it's not 2.1 because I have it working on 2.1.0-beta at http://dev.reticent.net/full_calendar

**Comment by tedhill** [comment]
I changed the line 28 in ready.js

```
    events: "/full_calendar/events/feed",
```

to

```
    events: "/gamefinderbuddy/full_calendar/events/feed",
```

and it works :)

Thanks Silas.

**Comment by silasmontgomery** [comment]
You're welcome and thanks for your interest!

**Comment by joshdcid** [comment]
I have the same problem with cake 2.0 
Notice (8): Undefined index: start [APP/Plugin/FullCalendar/Controller/EventsController.php, line 83]
Notice (8): Undefined index: end [APP/Plugin/FullCalendar/Controller/EventsController.php, line 83]
Notice (8): Undefined variable: data [APP/Plugin/FullCalendar/Controller/EventsController.php, line 104]
null
what can i do?

**Comment by srs81** [comment]
Is your CakePHP app install on / or the WWW root? If not, you will have to manually change the path of the Javascript ... I have submitted a pull request that addresses this problem and allows it to run on any location on WWW, even outside of root.
